package main

const (
	scansText = `{{define "scans"}}// DON'T EDIT *** generated by scaneo *** DON'T EDIT //

package {{.PackageName}}

import (
	"database/sql"
	{{- range $i, $import := .Import }}
	"{{ $import }}"
	{{- end }}
)

{{range .Tokens}}func {{$.Visibility}}can{{title .Name}}(r *sql.Row) ({{ if .Selector }}{{ .Selector }}.{{ end }}{{.Name}}, error) {
	var s {{ if .Selector }}{{ .Selector }}.{{ end }}{{.Name}}
	if err := r.Scan({{range .Fields}}
		&s.{{.Name}},{{end}}
	); err != nil {
		return {{ if .Selector }}{{ .Selector }}.{{ end }}{{.Name}}{}, err
	}
	return s, nil
}

func {{$.Visibility}}can{{title .Name}}s(rs *sql.Rows) ([]{{ if .Selector }}{{ .Selector }}.{{ end }}{{.Name}}, error) {
	structs := make([]{{ if .Selector }}{{ .Selector }}.{{ end }}{{.Name}}, 0, 16)
	var err error
	for rs.Next() {
		var s {{ if .Selector }}{{ .Selector }}.{{ end }}{{.Name}}
		if err = rs.Scan({{range .Fields}}
			&s.{{.Name}},{{end}}
		); err != nil {
			return nil, err
		}
		structs = append(structs, s)
	}
	if err = rs.Err(); err != nil {
		return nil, err
	}
	return structs, nil
}

{{end}}{{end}}`
)
